name: Mogies Smart Contracts

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install os deps
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get clean && sudo apt-get update
          sudo apt-get install -y build-essential libudev-dev libusb-1.0-0-dev
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: |
          npm install -g yarn
          yarn install
          yarn add -W hardhat-deploy-ethers
          yarn test
